# Copyright (C) 2020 GreenWaves Technologies
# All rights reserved.

# This software may be modified and distributed under the terms
# of the BSD license.  See the LICENSE file for details.

ifndef GAP_SDK_HOME
  $(error Source sourceme in gap_sdk first)
endif

include $(RULES_DIR)/pmsis_defs.mk

# MFCC
BUILD_DIR ?= BUILD
MFCCBUILD_DIR ?= $(CURDIR)/BUILD_MFCC
GAP9_SDK_DIR ?= /usr/scratch/wetterhorn/cioflanc/tools/gap_sdk_private/
DSP_DIR ?= $(GAP9_SDK_DIR)tools/autotiler_v3/DSP_Libraries/
AUTOTILER_DIR ?= $(GAP9_SDK_DIR)tools/autotiler_v3/Autotiler/
DSP_LUT_DIR ?= $(GAP9_SDK_DIR)tools/autotiler_v3/DSP_Libraries/LUT_Tables/
AUTOTILER_MFCC_DIR ?= $(GAP9_SDK_DIR)tools/autotiler_v3/Generators/MFCC/
WAVIO_DIR ?= $(GAP9_SDK_DIR)libs/gap_lib/include/

APP_CFLAGS += -I$(MFCCBUILD_DIR)
APP_CFLAGS += -I$(DSP_DIR)
APP_CFLAGS += -I$(DSP_LUT_DIR)
APP_CFLAGS += -I$(AUTOTILER_DIR)
APP_CFLAGS += -I$(AUTOTILER_MFCC_DIR)
APP_CFLAGS += -I$(WAVIO_DIR)

APP_SRCS  += $(DSP_DIR)FFT_Library.c 
APP_SRCS  += $(DSP_DIR)CmplxFunctions.c
APP_SRCS  += $(DSP_DIR)PreProcessing.c
APP_SRCS  += $(DSP_DIR)math_funcs.c
APP_SRCS  += $(DSP_DIR)MfccBasicKernels.c
APP_SRCS  += $(MFCCBUILD_DIR)/MfccKernels.c 
APP_SRCS  += $(GAP_LIB_PATH)/wav_io/wavIO.c  

include MfccModel.mk

mfcc:: gen_mfcc_code

# DORY
APP_CFLAGS += -DNUM_CORES=8
APP_CFLAGS += -IDORY_network/inc

APP_SRCS   += $(wildcard DORY_network/src/*.c)

FLASH_TYPE ?= HYPERFLASH
RAM_TYPE ?= HYPERRAM
ifeq '$(FLASH_TYPE)' 'MRAM'
READFS_FLASH = target/chip/soc/mram
endif

APP_CFLAGS += -DGAP_SDK=1
APP_CFLAGS += -DFLASH_TYPE=$(FLASH_TYPE)
APP_CFLAGS += -DUSE_$(FLASH_TYPE)
APP_CFLAGS += -DUSE_$(RAM_TYPE)

include vars.mk


# Application
APP_MODE=0
APP_CFLAGS += -I$(TARGET_BUILD_DIR)
APP_CFLAGS += -I$(GAP9_SDK_DIR)rtos/sfu/include

APP_SRCS   += Graph_L2_Descr.c
APP_SRCS   += $(GAP9_SDK_DIR)/rtos/sfu/SFU_RT.c
APP_SRCS   += dac.c
APP_SRCS   += denoiser.c

# io=uart
io=host

WAV_FILE=/usr/scratch/sassauna2/cioflanc/dolphinGSC/speech_commands_v0.02/right/94de6a6a_nohash_4.wav

DEMO        = 1
FLASH_TYPE  = MRAM
RAM_TYPE    = DEFAULT
FREQ_CL     = 50
FREQ_FC     = 50
FREQ_SFU    = 200
VOLTAGE     = 650


#############################################
### 	External Mem Settings
#############################################
EXEC_FROM_FLASH ?= false
ifeq '$(FLASH_TYPE)' 'HYPER'
    MODEL_L3_FLASH=AT_MEM_L3_HFLASH
else ifeq '$(FLASH_TYPE)' 'MRAM'
    MODEL_L3_FLASH=AT_MEM_L3_MRAMFLASH
    READFS_FLASH = mram
    EXEC_FROM_FLASH=true
else ifeq '$(FLASH_TYPE)' 'QSPI'
    MODEL_L3_FLASH=AT_MEM_L3_QSPIFLASH
    READFS_FLASH = target/board/devices/spiflash
else ifeq '$(FLASH_TYPE)' 'OSPI'
    MODEL_L3_FLASH=AT_MEM_L3_OSPIFLASH
else ifeq '$(FLASH_TYPE)' 'DEFAULT'
    MODEL_L3_FLASH=AT_MEM_L3_DEFAULTFLASH
endif

ifeq '$(RAM_TYPE)' 'HYPER'
    MODEL_L3_RAM=AT_MEM_L3_HRAM
else ifeq '$(RAM_TYPE)' 'QSPI'
    MODEL_L3_RAM=AT_MEM_L3_QSPIRAM
else ifeq '$(RAM_TYPE)' 'OSPI'
    MODEL_L3_RAM=AT_MEM_L3_OSPIRAM
else ifeq '$(RAM_TYPE)' 'DEFAULT'
    MODEL_L3_RAM=AT_MEM_L3_DEFAULTRAM
endif

SILENT?=1
CHECKSUM?=0
DEBUG?=1
DEBUG_STFT?=0

STFT_FRAMES?=49
FRAME_SIZE=640
FRAME_STEP=320
FRAME_NFFT=1024
NUM_FRAME_OVERLAP=3
SAMPLING_FREQ=16000
AT_INPUT_WIDTH=257 #1088
AT_INPUT_HEIGHT=1


ifeq '$(TARGET_CHIP)' 'GAP9_V2'
	FREQ_CL?=370
	FREQ_FC?=370
	FREQ_SFU?=370

	CLUSTER_STACK_SIZE=4096
	CLUSTER_SLAVE_STACK_SIZE=2048
# 	CLUSTER_STACK_SIZE=8192
# 	CLUSTER_SLAVE_STACK_SIZE=4096
# 	CLUSTER_STACK_SIZE=16384
# 	CLUSTER_SLAVE_STACK_SIZE=8192
	CLUSTER_NUM_CORES=8
	TOTAL_STACK_SIZE=$(shell expr $(CLUSTER_STACK_SIZE) \+ $(CLUSTER_SLAVE_STACK_SIZE) \* $(CLUSTER_NUM_CORES))
	MODEL_L1_MEMORY?=$(shell expr 120000 \- $(TOTAL_STACK_SIZE))
	MODEL_L2_MEMORY?=1000000
	MODEL_L3_MEMORY?=8000000

else
	ifeq '$(TARGET_CHIP)' 'GAP9'
		FREQ_CL?=50
		FREQ_FC?=50

		CLUSTER_STACK_SIZE=4096
		CLUSTER_SLAVE_STACK_SIZE=2048
		CLUSTER_NUM_CORES=8
		TOTAL_STACK_SIZE=$(shell expr $(CLUSTER_STACK_SIZE) \+ $(CLUSTER_SLAVE_STACK_SIZE) \* $(CLUSTER_NUM_CORES))
		MODEL_L1_MEMORY=$(shell expr 120000 \- $(TOTAL_STACK_SIZE))
		MODEL_L2_MEMORY=300000
		MODEL_L3_MEMORY=8000000

	else
		ifeq '$(TARGET_CHIP)' 'GAP8_V3'
			FREQ_CL?=175
		else
			FREQ_CL?=50
		endif
		FREQ_FC?=250

		CLUSTER_STACK_SIZE=8096
		CLUSTER_SLAVE_STACK_SIZE=8096
		CLUSTER_NUM_CORES=8
		TOTAL_STACK_SIZE=$(shell expr $(CLUSTER_STACK_SIZE) \+ $(CLUSTER_SLAVE_STACK_SIZE) \* 7)
		MODEL_L1_MEMORY=$(shell expr 60000 \- $(TOTAL_STACK_SIZE))
		MODEL_L2_MEMORY=350000
		MODEL_L3_MEMORY=8000000
	endif
endif
MODEL_SIZE_CFLAGS = -DAT_INPUT_HEIGHT=$(AT_INPUT_HEIGHT) -DAT_INPUT_WIDTH=$(AT_INPUT_WIDTH) -DAT_INPUT_COLORS=$(AT_INPUT_COLORS)

PMSIS_OS=freertos

#C flags
APP_CFLAGS += -O2 -s -mno-memcpy -fno-tree-loop-distribute-patterns -w -DPERF # -DPRINTDEB -DPRINT_INOUT

#include paths
APP_CFLAGS += -I.

#defines
APP_CFLAGS += -DAT_MODEL_PREFIX=$(MODEL_PREFIX) $(MODEL_SIZE_CFLAGS)
APP_CFLAGS += -DSTACK_SIZE=$(CLUSTER_STACK_SIZE) -DSLAVE_STACK_SIZE=$(CLUSTER_SLAVE_STACK_SIZE) 
APP_CFLAGS += -DFREQ_FC=$(FREQ_FC) -DFREQ_CL=$(FREQ_CL) -DFREQ_SFU=$(FREQ_SFU) -DVOLTAGE=$(VOLTAGE)
APP_CFLAGS += -DAT_IMAGE=$(IMAGE) -DWAV_FILE=$(WAV_FILE) # -DWRITE_WAV #-DPRINT_AT_INPUT #-DPRINT_WAV 

APP_CFLAGS += -DSTFT_FRAMES=$(STFT_FRAMES)
APP_CFLAGS += -DFRAME_SIZE=$(FRAME_SIZE)
APP_CFLAGS += -DFRAME_STEP=$(FRAME_STEP)
APP_CFLAGS += -DFRAME_NFFT=$(FRAME_NFFT)
APP_CFLAGS += -DNUM_FRAME_OVERLAP=$(NUM_FRAME_OVERLAP)
APP_CFLAGS += -DSAMPLING_FREQ=$(SAMPLING_FREQ)
APP_CFLAGS += -DAT_INPUT_WIDTH=$(AT_INPUT_WIDTH)
APP_CFLAGS += -DAT_INPUT_HEIGHT=$(AT_INPUT_HEIGHT)
APP_CFLAGS += -DMAX_L2_BUFFER=$(MODEL_L2_MEMORY)
APP_CFLAGS += -DDEMO=$(DEMO)
APP_CFLAGS += -DBUILD_DIR="../../.."


APP_LDFLAGS		+= -lm


ifeq ($(platform), gvsoc)
	APP_CFLAGS += -DPERF
else
	ifeq ($(APP_MODE), 0)
	APP_CFLAGS += -DAUDIO_EVK 
	else
	APP_CFLAGS += -DPERF -DAUDIO_EVK 
	endif
endif

ifeq ($(SILENT), 1)
	APP_CFLAGS += -DSILENT
endif

ifeq ($(CHECKSUM), 1)
	APP_CFLAGS += -DCHECKSUM
endif

ifeq ($(DEBUG_STFT), 1)
	APP_CFLAGS += -DPRINTDEB
endif

ifeq ($(DEBUG), 1)
	APP_CFLAGS += -DPRINTDEBUG
endif

clean:: clean_mfcc_code
	rm -rf BUILD*

$(info APP_SRCS... $(APP_SRCS))
$(info APP_CFLAGS... $(APP_CFLAGS))

include $(RULES_DIR)/pmsis_rules.mk