// flag_DW                        1
// out_mult                       18
// out_mult2                      0
// out_shift                      18
// FLAG_BATCHNORM                 1
// FLAG_RELU                      1
// weight_T                       0
// to_compute_acc_in              0
// to_compute_acc_out             0
// test_location                  L3
// tile_dim_h                     1
// tile_dim_w                     1
// optional                       conv
// conv_order                     PULP-NN
// type                           char
// func_name                      layerConvDWBNRelu9
// l1_x_offset                    0
// l1_y_offset                    17924
// l1_W_offset                    35848
// l1_k_offset                    36490
// l1_lambda_offset               37006
// k_size_byte                    512
// lambda_size_byte               1024
// k_tile_size_byte               70
// lambda_tile_size_byte          140
// tile_dim_nof                   8
// tile_dim_nif                   8
// border                         1
// nof                            256
// nif                            256
// h                              16
// w                              16
// fs1                            3
// fs2                            3
// conv_overlap1                  2
// conv_overlap2                  2
// has_bias                       0
// padding                        1
// stride                         1
// x_h                            16
// x_w                            16
// x_data_size_byte               1
// x_tile_size_nif                35
// x_tile_size_h                  16
// x_tile_size_w                  16
// x_tile_size_byte               8960
// x_stride_w_byte                4096
// x_stride_c_byte                256
// x_length_nif_px                35
// x_length_nif_byte              35
// x_length_h_px                  16
// x_length_w_byte                16
// x_tile_size_nif_last           11
// x_tile_size_h_last             16
// x_tile_size_w_last             16
// x_length_nif_px_last           11
// x_length_nif_byte_last         11
// x_length_h_px_last             16
// x_length_w_byte_last           16
// x_tile_size_byte_first         8960
// x_length_nif_px_first          35
// x_length_nif_byte_first        35
// x_length_h_px_first            16
// x_length_w_byte_first          16
// W_nof                          256
// b_tile_size_byte               35
// W_nif                          1
// W_data_size_byte               1
// W_tile_size_nof                35
// W_tile_size_nif                1
// W_tile_size_byte               315
// W_stride_nof_byte              9
// W_stride_hw_byte               1
// W_length_nif_byte              1
// W_tile_size_nof_last           11
// W_tile_size_nif_last           1
// W_length_nif_byte_last         1
// W_tile_size_byte_first         315
// W_length_nif_byte_first        1
// b_size_byte                    256
// l2_off_k                       2304
// l2_off_lambda                  2816
// y_h                            16
// y_w                            16
// y_data_size_byte               1
// y_tile_size_nof                35
// y_tile_size_h                  16
// y_tile_size_w                  16
// y_tile_size_byte               8960
// y_stride_w_byte                4096
// y_stride_c_byte                256
// y_length_nof_px                35
// y_length_nof_byte              35
// y_length_h_px                  16
// y_length_w_byte                16
// y_tile_size_nof_last           11
// y_tile_size_h_last             16
// y_tile_size_w_last             16
// y_length_nof_px_last           11
// y_length_w_byte_last           16
// y_length_nof_byte_last         11


#include "pulp.h"
#include "dory.h"
#include "stats.h"

void  layerConvDWBNRelu9(
  unsigned int l2_x,
  unsigned int l2_y,
  unsigned int l2_W,
  unsigned int l1_buffer,
  unsigned int out_mult_in,
  unsigned int out_shift_in
);
