// flag_DW                        0
// out_mult                       31
// out_mult2                      0
// out_shift                      19
// FLAG_BATCHNORM                 1
// FLAG_RELU                      1
// weight_T                       0
// to_compute_acc_in              0
// to_compute_acc_out             0
// test_location                  L3
// tile_dim_h                     2
// tile_dim_w                     8
// optional                       conv
// conv_order                     PULP-NN
// type                           char
// func_name                      layerConvBNRelu0
// l1_x_offset                    0
// l1_y_offset                    11530
// l1_W_offset                    40206
// l1_k_offset                    41946
// l1_lambda_offset               42014
// k_size_byte                    64
// lambda_size_byte               128
// k_tile_size_byte               64
// lambda_tile_size_byte          128
// tile_dim_nof                   1
// tile_dim_nif                   1
// border                         1
// nof                            32
// nif                            3
// h                              128
// w                              128
// fs1                            3
// fs2                            3
// conv_overlap1                  1
// conv_overlap2                  1
// has_bias                       0
// padding                        1
// stride                         2
// x_h                            128
// x_w                            128
// x_data_size_byte               1
// x_tile_size_nif                3
// x_tile_size_h                  113
// x_tile_size_w                  17
// x_tile_size_byte               5763
// x_stride_w_byte                384
// x_stride_c_byte                3
// x_length_nif_px                3
// x_length_nif_byte              3
// x_length_h_px                  113
// x_length_w_byte                17
// x_tile_size_nif_last           3
// x_tile_size_h_last             17
// x_tile_size_w_last             17
// x_length_nif_px_last           3
// x_length_nif_byte_last         3
// x_length_h_px_last             17
// x_length_w_byte_last           17
// x_tile_size_byte_first         5763
// x_length_nif_px_first          3
// x_length_nif_byte_first        3
// x_length_h_px_first            113
// x_length_w_byte_first          17
// W_nof                          32
// b_tile_size_byte               32
// W_nif                          3
// W_data_size_byte               1
// W_tile_size_nof                32
// W_tile_size_nif                3
// W_tile_size_byte               864
// W_stride_nof_byte              27
// W_stride_hw_byte               3
// W_length_nif_byte              3
// W_tile_size_nof_last           32
// W_tile_size_nif_last           3
// W_length_nif_byte_last         3
// W_tile_size_byte_first         864
// W_length_nif_byte_first        3
// b_size_byte                    32
// l2_off_k                       864
// l2_off_lambda                  928
// y_h                            64
// y_w                            64
// y_data_size_byte               1
// y_tile_size_nof                32
// y_tile_size_h                  56
// y_tile_size_w                  8
// y_tile_size_byte               14336
// y_stride_w_byte                2048
// y_stride_c_byte                32
// y_length_nof_px                32
// y_length_nof_byte              32
// y_length_h_px                  56
// y_length_w_byte                8
// y_tile_size_nof_last           32
// y_tile_size_h_last             8
// y_tile_size_w_last             8
// y_length_nof_px_last           32
// y_length_w_byte_last           8
// y_length_nof_byte_last         32


#include "pulp.h"
#include "dory.h"
#include "stats.h"

void  layerConvBNRelu0(
  unsigned int l2_x,
  unsigned int l2_y,
  unsigned int l2_W,
  unsigned int l1_buffer,
  unsigned int out_mult_in,
  unsigned int out_shift_in
);
