// flag_DW                        0
// out_mult                       23
// out_mult2                      0
// out_shift                      21
// FLAG_BATCHNORM                 1
// FLAG_RELU                      1
// weight_T                       0
// to_compute_acc_in              0
// to_compute_acc_out             0
// test_location                  L3
// tile_dim_h                     2
// tile_dim_w                     16
// optional                       conv
// conv_order                     PULP-NN
// type                           char
// func_name                      layerConvBNRelu2
// l1_x_offset                    0
// l1_y_offset                    12292
// l1_W_offset                    36872
// l1_k_offset                    40980
// l1_lambda_offset               41112
// k_size_byte                    128
// lambda_size_byte               256
// k_tile_size_byte               128
// lambda_tile_size_byte          256
// tile_dim_nof                   1
// tile_dim_nif                   1
// border                         0
// nof                            64
// nif                            32
// h                              64
// w                              64
// fs1                            1
// fs2                            1
// conv_overlap1                  0
// conv_overlap2                  0
// has_bias                       0
// padding                        0
// stride                         1
// x_h                            64
// x_w                            64
// x_data_size_byte               1
// x_tile_size_nif                32
// x_tile_size_h                  48
// x_tile_size_w                  4
// x_tile_size_byte               6144
// x_stride_w_byte                2048
// x_stride_c_byte                32
// x_length_nif_px                32
// x_length_nif_byte              32
// x_length_h_px                  48
// x_length_w_byte                4
// x_tile_size_nif_last           32
// x_tile_size_h_last             16
// x_tile_size_w_last             4
// x_length_nif_px_last           32
// x_length_nif_byte_last         32
// x_length_h_px_last             16
// x_length_w_byte_last           4
// x_tile_size_byte_first         6144
// x_length_nif_px_first          32
// x_length_nif_byte_first        32
// x_length_h_px_first            48
// x_length_w_byte_first          4
// W_nof                          64
// b_tile_size_byte               64
// W_nif                          32
// W_data_size_byte               1
// W_tile_size_nof                64
// W_tile_size_nif                32
// W_tile_size_byte               2048
// W_stride_nof_byte              32
// W_stride_hw_byte               32
// W_length_nif_byte              32
// W_tile_size_nof_last           64
// W_tile_size_nif_last           32
// W_length_nif_byte_last         32
// W_tile_size_byte_first         2048
// W_length_nif_byte_first        32
// b_size_byte                    64
// l2_off_k                       2048
// l2_off_lambda                  2176
// y_h                            64
// y_w                            64
// y_data_size_byte               1
// y_tile_size_nof                64
// y_tile_size_h                  48
// y_tile_size_w                  4
// y_tile_size_byte               12288
// y_stride_w_byte                4096
// y_stride_c_byte                64
// y_length_nof_px                64
// y_length_nof_byte              64
// y_length_h_px                  48
// y_length_w_byte                4
// y_tile_size_nof_last           64
// y_tile_size_h_last             16
// y_tile_size_w_last             4
// y_length_nof_px_last           64
// y_length_w_byte_last           4
// y_length_nof_byte_last         64


#include "pulp.h"
#include "dory.h"
#include "stats.h"

void  layerConvBNRelu2(
  unsigned int l2_x,
  unsigned int l2_y,
  unsigned int l2_W,
  unsigned int l1_buffer,
  unsigned int out_mult_in,
  unsigned int out_shift_in
);
