  unsigned int dma_read_evt_W;
  unsigned int dma_read_evt_b;
  unsigned int dma_read_evt_x;
  unsigned int dma_read_evt_x2;
  unsigned int dma_write_evt_y;
  int p_r, p_l, p_t, p_b;
  int last_nof_exec;
  int last_nif_exec;
  int last_h_exec;
  int last_w_exec;
  unsigned short x_tile_size_nif;
  unsigned short  x_tile_size_h;
  unsigned short  x_tile_size_w;
  unsigned short  x_tile_size_byte;
  unsigned short  x_length_h_px;
  unsigned short  x_length_nif_byte;
  int pad_offset_h=0, pad_offset_w=0;
  unsigned short  W_tile_size_nof;
  unsigned short  W_tile_size_nif;
  unsigned short  W_tile_size_byte;
  unsigned short W_length_nif_byte;
  char *x;
  char *x2;
  char *W;
  char *y;
  char *b;
  int has_bias;
  int x_tile_size_nif_exec;
  int x_tile_size_h_exec;
  int x_tile_size_w_exec;
  int y_tile_size_nof;
  int y_tile_size_h;
  int y_tile_size_w;
  int y_tile_size_byte;
  int y_length_h_px;
  int y_length_nof_byte;
// compute double buffering offsets and update db state
  int db_x;
  int db_W;
  int db_y;
  int exec_db_x;
  int exec_db_W;
  char *im2col;
  uint16_t out_mult;
  uint16_t out_shift;
  int16_t *k;
  int32_t *lambda;
  int32_t *pInBufferAcc;
  int32_t *pOutBufferAcc;
  unsigned int dma_read_evt_acc_in;
  unsigned int dma_read_evt_lambda;
  unsigned int dma_read_evt_k;
  int exec_db_acc_in;
  int db_acc_in;
  int db_acc_out;
  int exec_db_acc_out;
  unsigned int dma_write_evt_acc_out;
  unsigned int dma_read_evt_acc_out;
  int acc_out_tile_size_byte;
  int acc_out_tile_size_w;
extern   int acc_in_tile_size_byte;
extern   int acc_in_tile_size_w;
